version: '3.8'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: travelDB
      POSTGRES_USER: travelDBUser
      POSTGRES_PASSWORD: travelfweSS24
    ports:
      - '5432:5432'
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
    driver: local
