/* tslint:disable */
/* eslint-disable */
/**
 * api-fwe-ss-24
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface DestinationsBody
 */
export interface DestinationsBody {

    /**
     * @type {any}
     * @memberof DestinationsBody
     */
    name: any;

    /**
     * @type {any}
     * @memberof DestinationsBody
     */
    description?: any;

    /**
     * @type {any}
     * @memberof DestinationsBody
     */
    startDate: any;

    /**
     * @type {any}
     * @memberof DestinationsBody
     */
    endDate: any;

    /**
     * @type {any}
     * @memberof DestinationsBody
     */
    activities: any;

    /**
     * @type {any}
     * @memberof DestinationsBody
     */
    photos?: any;

    /**
     * @type {any}
     * @memberof DestinationsBody
     */
    rating?: any;

    /**
     * @type {any}
     * @memberof DestinationsBody
     */
    trips: any;
}
