/* tslint:disable */
/* eslint-disable */
/**
 * api-fwe-ss-24
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface DestinationsIdBody
 */
export interface DestinationsIdBody {

    /**
     * @type {any}
     * @memberof DestinationsIdBody
     */
    name?: any;

    /**
     * @type {any}
     * @memberof DestinationsIdBody
     */
    description?: any;

    /**
     * @type {any}
     * @memberof DestinationsIdBody
     */
    startDate?: any;

    /**
     * @type {any}
     * @memberof DestinationsIdBody
     */
    endDate?: any;

    /**
     * @type {any}
     * @memberof DestinationsIdBody
     */
    activities?: any;

    /**
     * @type {any}
     * @memberof DestinationsIdBody
     */
    photos?: any;

    /**
     * @type {any}
     * @memberof DestinationsIdBody
     */
    rating?: any;

    /**
     * @type {any}
     * @memberof DestinationsIdBody
     */
    trips?: any;
}
