/* tslint:disable */
/* eslint-disable */
/**
 * api-fwe-ss-24
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface TripsIdBody
 */
export interface TripsIdBody {

    /**
     * @type {any}
     * @memberof TripsIdBody
     */
    name?: any;

    /**
     * @type {any}
     * @memberof TripsIdBody
     */
    description?: any;

    /**
     * @type {any}
     * @memberof TripsIdBody
     */
    startDate?: any;

    /**
     * @type {any}
     * @memberof TripsIdBody
     */
    endDate?: any;

    /**
     * @type {any}
     * @memberof TripsIdBody
     */
    image?: any;

    /**
     * @type {any}
     * @memberof TripsIdBody
     */
    participants?: any;

    /**
     * @type {any}
     * @memberof TripsIdBody
     */
    destinations?: any;
}
